### ISSUE TITLE
Packagist still ask for laravel 5.4

### ISSUE THREAD

**Issue by Azakur4** [laravel-notification-channels/ionic-push-notifications#32]
When i try to install this via composer i get an error for the version of laravel.

actually im running laravel 5.5 in ur composer say that u support laravel 5.5.* but in packagist still saying laravel 5.4.*

**Comment by JayBizzle** [comment]
I have just push [v1.0.5](https://github.com/laravel-notification-channels/ionic-push-notifications/releases/tag/1.0.5) which should fix the issue.

Give it a try and let me know.

Thanks

**Comment by Azakur4** [comment]
Packagist still showing version 1.0.4

https://packagist.org/packages/laravel-notification-channels/ionic-push-notifications

**Comment by JayBizzle** [comment]
Check now...

**Comment by Azakur4** [comment]
thanks is updated now
